[package]
name = "advent_of_code_10_adapter_array"
version = "0.1.0"
authors = ["Vladimir Medovy <34925522+vmedovy@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
